### ISSUE TITLE
Implement State Saving/Loading

### ISSUE THREAD

**Issue by cestes-csumb** [DannyJacoby/CST438_P3_SP21#15]
Determine what will be saved upon hibernating application, closing application, logging out, etc
Restore upon starting the gameplay activity again.

**Comment by cestes-csumb** [comment]
### **Open new branch.**

**Comment by bcarbonneau** [comment]
User and enemy data is now saved upon hitting the back button in the game activity and returning to the menu activity. The data is restored when reopening the game activity. Note: Currently closing the app before using the back button to return to the menu activity results in lost progress. May need adjustments later.

**Comment by cestes-csumb** [comment]
I believe we've completed implementation of this as of https://github.com/DannyJacoby/CST438_P3_SP21/commit/152c7c8d50ca48e41d82bb7333f184caed9823c8
